### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by Flowtter** [Obeeron/UniversimBot#1]
Hi,
Consider moving the python code into an `src` folder to avoid code pollution. This is how most python applications are coded, so you can create packages later on. I suggest you look at an example like [crispy](https://github.com/Flowtter/crispy/tree/master/src).

Also consider adding a Makefile to help with the virtual environment [here](https://earthly.dev/blog/python-makefile/).

First python project, neat 🥳

**Comment by charlestrodet** [comment]
> Consider moving the python code into an src folder to avoid code pollution. 

Since I only have one small py file for now, making an src folder would be overkill

> I'm not sure if Docker related files should also be moved to a Docker folder.

Then I'd have to manually specify the location of the Dockerfile

> Also consider adding a Makefile to help with the virtual environment [here](https://earthly.dev/blog/python-makefile/) instead of a Dockerfile, or to improve the project.

Dockerfile is here to provide a layer of security an ease the use of dependencies on the server I run the bot on.
Though I'll surely add a makefile when the bot grows bigger because I'll have to split it into different files
